Fixed issue where metadata would come with garbage
IRNAS/ppk2-api-python pull request #50
Opened 2024-12-17 14:29 UTC by Tjoms99

Investigated the PR/issue discussed here #49. 
 
 Turns out not properly exiting a program running the PPK2 influences the next PPK2 session.  Setting up the metadata the first time will throw an exception due to the garbage data (from the previous session) that comes a long with it. Physically turning the PPK2 on and off using the switch resolves this issue, but that’s inconvenient to do every time; So I’ve added a software fix here :)

2024-12-27 09:22 UTC, RmThrt commented
Thanks for the fix, it helped to figure out the way my test work! the fix sounds good to me

2025-02-21 09:03 UTC, MrKevinWeiss commented
Also tested and it works for me!

2025-02-21 09:03 UTC, MrKevinWeiss commented
This is on 4.2.0 and 4.2.1 fw.

2025-02-28 10:37 UTC, mstixenberger commented
works fine, thank you!

2025-05-05 10:15 UTC, bobatsar commented
Works also on my side.  @wlgrd is it possible to merge it into master?

2025-10-21 01:52 UTC, tphillips-ict commented
+1 Can we merge this? Running into the same issue.

Is this project still actively maintained?

2026-03-06 11:06 UTC, MrKevinWeiss requested changes
A few small things, but at least now we can move!

2026-03-06 11:06 UTC, MrKevinWeiss commented on src/ppk2_api/ppk2_api.py
> +    def get_modifiers(self, retries=2):
```suggestion
    def get_modifiers(self, retries=4):
```

I have seen this occurring in our devices, maybe a bit of extra time would help?

2026-03-06 11:06 UTC, MrKevinWeiss commented on src/ppk2_api/ppk2_api.py
> +        return None
```suggestion
        for attempt in range(1, retries + 1):
            # Send command to request metadata
            self._write_serial((PPK2_Command.GET_META_DATA, ))
            try:
                metadata = self._read_metadata()    
                ret = self._parse_metadata(metadata)
                logging.info(f"Attempt {attempt}/{retries} - Got metadata from PPK2")

                return ret
            except ValueError as e:
                logging.warning(f"Attempt {attempt}/{retries} - Failed to get valid PPK2 metadata: {e}")
                # Wait a bit in case device was previously running
                time.sleep(0.5)
                # Clear anything in the buffer
                self.ser.read(self.ser.in_waiting)
                # If this wasn't the last attempt, we try again by sending GET_META_DATA again.
        raise IOError("Failed to get modifiers after multiple attempts. Reconnect device if this persists.")
```

I would try not to use prints here and rather logging to keep the stdout clean, logging allows a bit more control from the application side.

I think also throwing a proper exception if the modifiers are not there is better, then the applications would run uncalibrated, causing worse problems in the future... I have seen it before.

I also suggested (but didn't test) a way to hopefully harden the recovery process...

2026-03-09 12:12 UTC, Tjoms99 commented on src/ppk2_api/ppk2_api.py
> +        return None
I think, in hindsight, that the best way to solve this problem is to parse the metadata out from the garbage data (as it is in there). It feels like its the proper way to do it anyways, even on "clean" runs + it becomes more robust. Then, i think we can also remove the retries. 

If it fails, raising an IOError is a very good suggestion! 

I dont have time to look this before the weekend, but i would like to hear your thoughts on the suggestion above before continuing.

2026-03-09 14:30 UTC, MrKevinWeiss commented on src/ppk2_api/ppk2_api.py
> +        return None
I haven't closely looked into the output or the complexity of the parsing... If you think it is easy enough (and robust across the various PPK versions) then we can give it a try.  Solving hardware problems at the root is always better than adding retries and timeouts (though not always possible).

I am happy to test across firmware versions if you think you have it.  Otherwise, I have implemented this patch (or close enough to this patch) and am running tests with it.

2026-04-14 14:16 UTC, Tjoms99 commented
Did another pass on this locally and verified it against a connected PPK2.

  A couple of extra things came up while testing/integrating this in other code using the API:

  - `get_modifiers()` is now tightened up so it either succeeds or raises, instead of returning a mixed `True` / `None`
  - added return type hints in `ppk2_api.py` for the main API methods so the return contracts are a bit clearer
  - fixed the compatibility issue in `src/power_profiler.py` where `get_samples()` was still treated like a flat list instead of `(samples, raw_digital)`

  I also removed the library-side logger usage that was ending up affecting my main application logger outside of ppk2. Hard failures now just raise instead of log-and-continue.

  Verified by running:
  `python3 examples/example_measure_mw.py`

  This still works on my side with a connected PPK2 (`/dev/ttyACM0`) and streams measurements as expected. How does it look on your end?

2026-05-07 10:10 UTC, MrKevinWeiss commented
Just got back from vacation,  I will try to find some time either today or tomorrow for testing and reviewing!

2026-05-07 10:10 UTC, MrKevinWeiss commented
oh 3 weeks old... I guess that slipped through the cracks :face_with_diagonal_mouth:

2026-05-07 10:27 UTC, MrKevinWeiss reviewed
I tested with `python3.13` but needed a change...

<details><summary>manual testing results with "fresh" ppk</summary>

```
(.venv) weiss@lobaro-laptop-kw:~/repos/ppk2-api-python$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
139.58 mW, Avg: 139.58 mW
27.09 mW, Avg: 83.34 mW
26.72 mW, Avg: 64.46 mW
26.66 mW, Avg: 55.01 mW
26.45 mW, Avg: 49.30 mW
26.29 mW, Avg: 45.47 mW
26.24 mW, Avg: 42.72 mW
26.17 mW, Avg: 40.65 mW
26.04 mW, Avg: 39.03 mW
26.02 mW, Avg: 37.73 mW
25.99 mW, Avg: 36.66 mW
25.95 mW, Avg: 35.77 mW
25.9 mW, Avg: 35.01 mW
25.83 mW, Avg: 34.35 mW
26.51 mW, Avg: 33.83 mW
26.94 mW, Avg: 33.40 mW
26.71 mW, Avg: 33.01 mW
27.01 mW, Avg: 32.67 mW
27.01 mW, Avg: 32.37 mW
26.99 mW, Avg: 32.11 mW
27.43 mW, Avg: 31.88 mW
27.78 mW, Avg: 31.70 mW
30.21 mW, Avg: 31.63 mW

28.85 mW, Avg: 31.52 mW
(.venv) weiss@lobaro-laptop-kw:~/repos/ppk2-api-python$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
155.98 mW, Avg: 155.98 mW
26.94 mW, Avg: 91.46 mW
26.68 mW, Avg: 69.87 mW
26.61 mW, Avg: 59.05 mW
26.38 mW, Avg: 52.52 mW
26.22 mW, Avg: 48.13 mW
26.16 mW, Avg: 45.00 mW
26.09 mW, Avg: 42.63 mW
26.09 mW, Avg: 40.79 mW
25.98 mW, Avg: 39.31 mW
25.96 mW, Avg: 38.10 mW
25.92 mW, Avg: 37.08 mW
25.89 mW, Avg: 36.22 mW
25.84 mW, Avg: 35.48 mW
25.84 mW, Avg: 34.84 mW
25.82 mW, Avg: 34.27 mW
26.67 mW, Avg: 33.83 mW
26.96 mW, Avg: 33.45 mW
26.99 mW, Avg: 33.11 mW
27.0 mW, Avg: 32.80 mW
26.99 mW, Avg: 32.52 mW
27.01 mW, Avg: 32.27 mW
28.76 mW, Avg: 32.12 mW
27.48 mW, Avg: 31.93 mW
^C30.57 mW, Avg: 31.87 mW
Traceback (most recent call last):
  File "/home/weiss/repos/ppk2-api-python/examples/example_measure_mw.py", line 107, in <module>
    main()
    ~~~~^^
  File "/home/weiss/repos/ppk2-api-python/examples/example_measure_mw.py", line 102, in main
    input("Press Enter to exit...\n")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

(.venv) weiss@lobaro-laptop-kw:~/repos/ppk2-api-python$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
131.61 mW, Avg: 131.61 mW
27.03 mW, Avg: 79.32 mW
26.74 mW, Avg: 61.79 mW
26.67 mW, Avg: 53.01 mW
26.45 mW, Avg: 47.70 mW
26.33 mW, Avg: 44.14 mW
26.21 mW, Avg: 41.58 mW
26.11 mW, Avg: 39.64 mW
26.07 mW, Avg: 38.14 mW
26.05 mW, Avg: 36.93 mW
26.0 mW, Avg: 35.93 mW
25.95 mW, Avg: 35.10 mW
25.9 mW, Avg: 34.39 mW
25.84 mW, Avg: 33.78 mW
26.46 mW, Avg: 33.29 mW
26.74 mW, Avg: 32.88 mW
26.8 mW, Avg: 32.53 mW
27.01 mW, Avg: 32.22 mW
26.99 mW, Avg: 31.95 mW
27.01 mW, Avg: 31.70 mW
27.43 mW, Avg: 31.50 mW
27.94 mW, Avg: 31.33 mW
29.77 mW, Avg: 31.27 mW

28.88 mW, Avg: 31.17 mW

```
</details>

2026-05-07 10:27 UTC, MrKevinWeiss commented on examples/example_measure_mw.py
> +from src.ppk2_api.ppk2_api import PPK2_API
```suggestion
from ppk2_api.ppk2_api import PPK2_API
```

2026-05-07 10:33 UTC, MrKevinWeiss commented on examples/example_measure_mw.py
> +from src.ppk2_api.ppk2_api import PPK2_API
Works with python3.10 (which is the oldest still supported) and I am a big fan of the type hints.

2026-05-07 10:38 UTC, MrKevinWeiss commented
If you add the small change and squash then I would be happy to merge.

2026-05-07 11:59 UTC, MrKevinWeiss commented
Hmmm testing on a firmware updated ppk I get the first few readings as 0...

<details>

```
$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
25.57 mW, Avg: 2.13 mW
26.42 mW, Avg: 4.00 mW
26.38 mW, Avg: 5.60 mW
26.33 mW, Avg: 6.98 mW
26.35 mW, Avg: 8.19 mW
26.33 mW, Avg: 9.26 mW
26.31 mW, Avg: 10.21 mW
26.42 mW, Avg: 11.06 mW
27.45 mW, Avg: 11.88 mW
27.43 mW, Avg: 12.62 mW
27.43 mW, Avg: 13.29 mW
27.43 mW, Avg: 13.91 mW
27.42 mW, Avg: 14.47 mW
27.43 mW, Avg: 14.99 mW
27.4 mW, Avg: 15.47 mW
29.27 mW, Avg: 15.98 mW
31.07 mW, Avg: 16.52 mW
31.01 mW, Avg: 17.02 mW
30.99 mW, Avg: 17.48 mW
30.97 mW, Avg: 17.92 mW
30.96 mW, Avg: 18.32 mW
30.93 mW, Avg: 18.71 mW
30.95 mW, Avg: 19.07 mW
32.2 mW, Avg: 19.44 mW
32.28 mW, Avg: 19.80 mW
32.28 mW, Avg: 20.14 mW
32.26 mW, Avg: 20.45 mW
32.22 mW, Avg: 20.76 mW
32.25 mW, Avg: 21.04 mW
32.24 mW, Avg: 21.32 mW
30.86 mW, Avg: 21.54 mW
28.22 mW, Avg: 21.70 mW
28.21 mW, Avg: 21.85 mW
28.22 mW, Avg: 21.99 mW
28.22 mW, Avg: 22.12 mW
28.22 mW, Avg: 22.25 mW
28.21 mW, Avg: 22.38 mW
28.19 mW, Avg: 22.50 mW
25.5 mW, Avg: 22.56 mW

24.68 mW, Avg: 22.60 mW
(.venv) weiss@lobaro-laptop-kw:~/repos/ppk2-api-python$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
25.2 mW, Avg: 2.10 mW
26.08 mW, Avg: 3.94 mW
26.05 mW, Avg: 5.52 mW
26.03 mW, Avg: 6.89 mW
26.03 mW, Avg: 8.09 mW
26.04 mW, Avg: 9.14 mW
26.03 mW, Avg: 10.08 mW
26.07 mW, Avg: 10.92 mW
27.22 mW, Avg: 11.74 mW
27.19 mW, Avg: 12.47 mW
27.2 mW, Avg: 13.14 mW
27.2 mW, Avg: 13.75 mW
27.19 mW, Avg: 14.31 mW
27.17 mW, Avg: 14.83 mW
27.19 mW, Avg: 15.30 mW
28.98 mW, Avg: 15.81 mW
30.83 mW, Avg: 16.35 mW
30.77 mW, Avg: 16.84 mW
30.74 mW, Avg: 17.31 mW
30.72 mW, Avg: 17.74 mW
30.69 mW, Avg: 18.14 mW
30.7 mW, Avg: 18.52 mW
30.66 mW, Avg: 18.88 mW
31.91 mW, Avg: 19.25 mW
32.03 mW, Avg: 19.61 mW
32.03 mW, Avg: 19.94 mW
32.01 mW, Avg: 20.26 mW
31.97 mW, Avg: 20.56 mW
32.0 mW, Avg: 20.85 mW
31.99 mW, Avg: 21.12 mW
30.57 mW, Avg: 21.34 mW
28.0 mW, Avg: 21.50 mW
27.95 mW, Avg: 21.65 mW
^CTraceback (most recent call last):
  File "/home/weiss/repos/ppk2-api-python/examples/example_measure_mw.py", line 107, in <module>
    main()
  File "/home/weiss/repos/ppk2-api-python/examples/example_measure_mw.py", line 102, in main
    input("Press Enter to exit...\n")
KeyboardInterrupt

(.venv) weiss@lobaro-laptop-kw:~/repos/ppk2-api-python$ python examples/example_measure_mw.py
Press Enter to exit...
PPK2 devices found: [('/dev/ttyACM0', 'D06D19AF')]
[('/dev/ttyACM0', 'D06D19AF')]
Connecting to /dev/ttyACM0
Initialized Power Profiler
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
-0.0 mW, Avg: 0.00 mW
25.59 mW, Avg: 2.13 mW
26.1 mW, Avg: 3.98 mW
26.1 mW, Avg: 5.56 mW
26.06 mW, Avg: 6.92 mW
26.04 mW, Avg: 8.12 mW
26.02 mW, Avg: 9.17 mW
25.98 mW, Avg: 10.10 mW
26.11 mW, Avg: 10.95 mW
27.19 mW, Avg: 11.76 mW
27.23 mW, Avg: 12.50 mW
27.19 mW, Avg: 13.16 mW
27.19 mW, Avg: 13.77 mW
27.19 mW, Avg: 14.33 mW
27.22 mW, Avg: 14.85 mW
27.22 mW, Avg: 15.32 mW
29.09 mW, Avg: 15.83 mW
30.82 mW, Avg: 16.37 mW
30.74 mW, Avg: 16.86 mW
30.76 mW, Avg: 17.33 mW
30.77 mW, Avg: 17.76 mW
30.74 mW, Avg: 18.17 mW

30.71 mW, Avg: 18.55 mW
```
</details>

2026-05-07 12:30 UTC, MrKevinWeiss commented
Also tested it in my current application removing the modification I needed and it seems to work well.

2026-05-13 10:30 UTC, MrKevinWeiss commented
ping

2026-05-18 14:26 UTC, Tjoms99 commented
Sorry for the late reply!

Regarding the 0 mw readings; I have done some testing and seems the result is valid, and the PPK is not delivering power during that period. 

LGTM!🎉

2026-05-19 07:20 UTC, MrKevinWeiss approved these changes
The change was addressed, big improvement, thanks!

2026-05-19 07:20 UTC, merged